---
title: "experiments-with-recycling"
author: "Emily Coco"
date: "9/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(naniar)
library(rpart)
library(rpart.plot)
library(data.table)
library(UpSetR)
library(rcompanion)
library(fitdistrplus)
library(crunch)
theme_set(theme_minimal())

parameters = c("max_use_intensity", "max_artifact_carry", "max_flake_size","max_nodules_size", "blank_prob", "scavenge_prob", "overlap","mu", "size_preference", "flake_preference","min_suitable_flake_size", "min_suitable_nodule_size", "strict_selection")

outputs = c("num.scav.events","total.recycled", "num.deposits",	"total.encounters",	"total.discards",	"total.manu.events", "total.retouches", "total.CR",	"total.RI")

alldata = alldata[alldata$size != "size",]

#alldata = alldata %>% filter(size != "size") %>%
#   mutate(total.RI = as.numeric(total.RI), 
#          total.CR = as.numeric(total.CR), 
#          num.scav.events = as.numeric(num.scav.events), 
#          total.recycled = as.numeric(total.recycled), 
#          num.deposits = as.numeric(num.deposits), 
#          total.encounters = as.numeric(total.encounters), 
#          total.discards = as.numeric(total.discards), 
#          total.manu.events = as.numeric(total.manu.events), 
#          total.retouches = as.numeric(total.retouches))



```

## What are the distributions of the output metrics?

```{r checking-assumptions}
plotNormalHistogram(alldata$total.RI)
distRI = alldata[!is.na(alldata$total.RI) & !is.nan(alldata$total.RI),]$total.RI
descdist(distRI, discrete=F)
rm(distRI)

plotNormalHistogram(alldata$total.CR)
distCR = alldata[!is.na(alldata$total.CR) & !is.nan(alldata$total.CR),]$total.CR
descdist(distCR, discrete=F)
rm(distCR)

plotNormalHistogram(alldata$num.scav.events)
distSE = alldata[!is.na(alldata$num.scav.events) & !is.nan(alldata$num.scav.events),]$num.scav.events
descdist(distSE, discrete=F)
rm(distSE)

plotNormalHistogram(alldata$total.recycled)
distTR = alldata[!is.na(alldata$total.recycled) & !is.nan(alldata$total.recycled),]$total.recycled
descdist(distTR, discrete=F)
rm(distTR)

plotNormalHistogram(alldata$num.deposits)
distND = alldata[!is.na(alldata$num.deposits) & !is.nan(alldata$num.deposits),]$num.deposits
descdist(distND, discrete=F)
rm(distND)

plotNormalHistogram(alldata$total.encounters)
distTE = alldata[!is.na(alldata$total.encounters) & !is.nan(alldata$total.encounters),]$total.encounters
descdist(distTE, discrete=F)
rm(distTE)

plotNormalHistogram(alldata$total.discards)
distTD = alldata[!is.na(alldata$total.discards) & !is.nan(alldata$total.discards),]$total.discards
descdist(distTD, discrete=F)
rm(distTD)

plotNormalHistogram(alldata$total.manu.events)
distME = alldata[!is.na(alldata$total.manu.events) & !is.nan(alldata$total.manu.events),]$total.manu.events
descdist(distME, discrete=F)
rm(distME)

plotNormalHistogram(alldata$total.retouches)
distTR = alldata[!is.na(alldata$total.retouches) & !is.nan(alldata$total.retouches),]$total.retouches
descdist(distTR, discrete=F)
rm(distTR)

```



## Where is there missing data for recycling intensity?

```{r missing-recycling-intensity}

outputs = c("num.scav.events","total.recycled", "num.deposits",	"total.encounters",	"total.discards",	"total.manu.events", "total.retouches", "total.CR",	"total.RI")

output_data = alldata[,c(outputs)]
gg_miss_var(output_data, show_pct = T)


facet_data = alldata[,c(parameters, outputs)]

for(p in parameters) {
  facet_data %>% group_by_at(p) %>%
    miss_var_summary()
}

```


