---
title: "Preliminary Data Analysis"
author: "Emily Coco"
date: "9/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(naniar)
library(rpart)
library(rpart.plot)
library(data.table)
library(UpSetR)
library(rcompanion)
library(fitdistrplus)
library(knitr)
library(kableExtra)
library(PerformanceAnalytics)
theme_set(theme_minimal())

parameters = c("max_use_intensity", "max_artifact_carry", "max_flake_size","max_nodules_size", "blank_prob", "scavenge_prob", "overlap","mu", "size_preference", "flake_preference","min_suitable_flake_size", "min_suitable_nodule_size", "strict_selection")

outputs = c("num.scav.events","total.recycled", "num.deposits",	"total.encounters",	"total.discards",	"total.manu.events", "total.retouches", "total.CR",	"total.RI")

#alldata = read_csv("~/eclipse-workspace/recycling-Java/output/sub_model.csv")

alldata = alldata[alldata$size != "size",]

alldata = alldata[!is.na(alldata$max_artifact_carry),]


#alldata = alldata %>% filter(size != "size") %>%
#   mutate(total.RI = as.numeric(total.RI), 
#          total.CR = as.numeric(total.CR), 
#          num.scav.events = as.numeric(num.scav.events), 
#          total.recycled = as.numeric(total.recycled), 
#          num.deposits = as.numeric(num.deposits), 
#          total.encounters = as.numeric(total.encounters), 
#          total.discards = as.numeric(total.discards), 
#          total.manu.events = as.numeric(total.manu.events), 
#          total.retouches = as.numeric(total.retouches))



```

## What are the distributions of the output metrics?

```{r checking-assumptions, eval=T}
plotNormalHistogram(alldata$total.RI)
distRI = alldata[!is.na(alldata$total.RI) & !is.nan(alldata$total.RI),]$total.RI
descdist(distRI, discrete=F)
descdist(distRI, discrete=T)
rm(distRI)

plotNormalHistogram(alldata$total.CR)
distCR = alldata[!is.na(alldata$total.CR) & !is.nan(alldata$total.CR),]$total.CR
descdist(distCR, discrete=F)
descdist(distCR, discrete=T)
rm(distCR)

plotNormalHistogram(alldata$num.scav.events)
distSE = alldata[!is.na(alldata$num.scav.events) & !is.nan(alldata$num.scav.events),]$num.scav.events
descdist(distSE, discrete=F)
descdist(distSE, discrete=T)
rm(distSE)

plotNormalHistogram(alldata$total.recycled)
distTR = alldata[!is.na(alldata$total.recycled) & !is.nan(alldata$total.recycled),]$total.recycled
descdist(distTR, discrete=F)
descdist(distTR, discrete=T)
rm(distTR)

plotNormalHistogram(alldata$num.deposits)
distND = alldata[!is.na(alldata$num.deposits) & !is.nan(alldata$num.deposits),]$num.deposits
descdist(distND, discrete=F)
descdist(distND, discrete=T)
rm(distND)

plotNormalHistogram(alldata$total.encounters)
distTE = alldata[!is.na(alldata$total.encounters) & !is.nan(alldata$total.encounters),]$total.encounters
descdist(distTE, discrete=F)
descdist(distTE, discrete=T)
rm(distTE)

plotNormalHistogram(alldata$total.discards)
distTD = alldata[!is.na(alldata$total.discards) & !is.nan(alldata$total.discards),]$total.discards
descdist(distTD, discrete=F)
descdist(distTD, discrete=T)
rm(distTD)

plotNormalHistogram(alldata$total.manu.events)
distME = alldata[!is.na(alldata$total.manu.events) & !is.nan(alldata$total.manu.events),]$total.manu.events
descdist(distME, discrete=F)
descdist(distME, discrete=T)
rm(distME)

plotNormalHistogram(alldata$total.retouches)
distTR = alldata[!is.na(alldata$total.retouches) & !is.nan(alldata$total.retouches),]$total.retouches
descdist(distTR, discrete=F)
descdist(distTR, discrete=T)
rm(distTR)

```



## Where is there missing data for recycling intensity?

```{r missing-recycling-intensity, eval=T, warning=F}

outputs = c("num.scav.events","total.recycled", "num.deposits",	"total.encounters",	"total.discards",	"total.manu.events", "total.retouches", "total.CR",	"total.RI")

output_data = alldata[,c(outputs)]
gg_miss_var(output_data, show_pct = T)


facet_data = alldata[,c(parameters, outputs)]

output_table_by_param = function(parameter) {
  return(
    facet_data %>% group_by_at(parameter) %>% miss_var_summary() %>%
        filter(variable %in% outputs) %>% kbl(caption = paste("Missing output values for values of", parameter)) %>%
      kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
  )
}

# output_table_by_param(parameters[1])
# output_table_by_param(parameters[2])
# output_table_by_param(parameters[3])
# output_table_by_param(parameters[4])
# output_table_by_param(parameters[5])
# output_table_by_param(parameters[6])
# output_table_by_param(parameters[7])
# output_table_by_param(parameters[8])
# output_table_by_param(parameters[9])
# output_table_by_param(parameters[10])
# output_table_by_param(parameters[11])
# output_table_by_param(parameters[12])
# output_table_by_param(parameters[13])


# output_table_by_exp = function() {
#   return(
#     facet_data %>% group_by_at(parameters) %>% miss_var_summary %>%
#     filter(n_miss != 0) %>% kbl(caption = paste("Missing output values for each experiment")) %>%
#       kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
#       )
# }
# 
# output_table_by_exp()

missing = (facet_data %>% group_by_at(parameters) %>% miss_var_summary %>% filter(n_miss != 0) %>% filter(variable == "total.RI") %>% filter(!is.na(mu)))[,c(1:13, 15)]

names(missing) <- gsub("_", "\n", names(missing))
chart.Correlation(missing, histogram=F, pch=2, method = "spearman", exact=F, cex.labels = 0.5)


```


