---
title: "Preliminary Data Analysis"
subtitle: "TWO TECHNOLOGY TYPES"
author: "Emily Coco"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(!require(fitdistrplus)){install.packages("fitdistrplus", repos = "https://cran.wustl.edu/")}
if(!require(knitr)){install.packages("knitr", repos = "https://cran.wustl.edu/")}
if(!require(kableExtra)){install.packages("kableExtra", repos = "https://cran.wustl.edu/")}
if(!require(PerformanceAnalytics)){install.packages("PerformanceAnalytics", repos = "https://cran.wustl.edu/")}
if(!require(jtools)){install.packages("jtools", repos = "https://cran.wustl.edu/")}
if(!require(broom.mixed)){install.packages("broom.mixed", repos = "https://cran.wustl.edu/")}
if(!require(ggstance)){install.packages("ggstance", repos = "https://cran.wustl.edu/")}
if(!require(huxtable)){install.packages("huxtable", repos = "https://cran.wustl.edu/")}

library(tidyverse)
library(naniar)
library(rpart)
library(rpart.plot)
library(data.table)
library(UpSetR)
library(rcompanion)
library(fitdistrplus)
library(knitr)
library(kableExtra)
library(PerformanceAnalytics)
library(jtools)
library(broom.mixed)
library(ggstance)
library(huxtable)

theme_set(theme_minimal())

parameters = c("max_use_intensity", "max_artifact_carry", "max_flake_size","max_nodules_size", "blank_prob", "scavenge_prob", "overlap", "mu", "size_preference", "flake_preference","min_suitable_flake_size", "min_suitable_nodule_size", "strict_selection")

# outputs = c("num.scav.events","total.recycled", "num.deposits",	"total.encounters",	"total.discards",	"total.manu.events", "total.retouches", "total.CR",	"total.RI")
outputs = colnames(alldata[c(22:34)])

#alldata = read_csv("~/eclipse-workspace/recycling-Java/output/sub_model.csv")

alldata = alldata[alldata$size != "size",]

alldata = alldata[!is.na(alldata$max_artifact_carry),]

two.tech = alldata[which(alldata$overlap == 1),]

rm(alldata)

```

## What are the distributions of the output metrics?
```{r checking-assumptions-two, eval=T, warning=F}
plotNormalHistogram(two.tech$total.RI)
distRI = two.tech[!is.na(two.tech$total.RI) & !is.nan(two.tech$total.RI),]$total.RI
descdist(distRI, discrete=F)
rm(distRI)

plotNormalHistogram(two.tech$total.CR)
distCR = two.tech[!is.na(two.tech$total.CR) & !is.nan(two.tech$total.CR),]$total.CR
descdist(distCR, discrete=F)
rm(distCR)

plotNormalHistogram(two.tech$num.scav.events)
distSE = two.tech[!is.na(two.tech$num.scav.events) & !is.nan(two.tech$num.scav.events),]$num.scav.events
descdist(distSE, discrete=T)
rm(distSE)

plotNormalHistogram(two.tech$num.discard.events)
distDE = two.tech[!is.na(two.tech$num.discard.events) & !is.nan(two.tech$num.discard.events),]$num.discard.events
descdist(distDE, discrete=T)
rm(distDE)

plotNormalHistogram(two.tech$num.rcycl.obj.made)
distRO = two.tech[!is.na(two.tech$num.rcycl.obj.made) & !is.nan(two.tech$num.rcycl.obj.made),]$num.rcycl.obj.made
descdist(distRO, discrete=T)
rm(distRO)

plotNormalHistogram(two.tech$num.retouch.events)
distRE = two.tech[!is.na(two.tech$num.retouch.events) & !is.nan(two.tech$num.retouch.events),]$num.retouch.events
descdist(distRE, discrete=T)
rm(distRE)

plotNormalHistogram(two.tech$num.blank.events)
distBE = two.tech[!is.na(two.tech$num.blank.events) & !is.nan(two.tech$num.blank.events),]$num.blank.events
descdist(distBE, discrete=T)
rm(distBE)

plotNormalHistogram(two.tech$total.recycled)
distTR = two.tech[!is.na(two.tech$total.recycled) & !is.nan(two.tech$total.recycled),]$total.recycled
descdist(distTR, discrete=T)
rm(distTR)

plotNormalHistogram(two.tech$cum.deposits)
distCD = two.tech[!is.na(two.tech$cum.deposits) & !is.nan(two.tech$cum.deposits),]$cum.deposits
descdist(distCD, discrete=T)
rm(distCD)

plotNormalHistogram(two.tech$cum.encounters)
distCE = two.tech[!is.na(two.tech$cum.encounters) & !is.nan(two.tech$cum.encounters),]$cum.encounters
descdist(distCE, discrete=T)
rm(distCE)

```

## Where is there missing data for recycling intensity?

```{r missing-recycling-intensity, eval=T, warning=F, message=F}

facet_data = two.tech[,c(parameters, outputs)]

output_table_by_param = function(parameter) {
  return(
    facet_data %>% group_by_at(parameter) %>% miss_var_summary() %>%
        filter(variable %in% outputs) %>% kbl(caption = paste("Missing output values for values of", parameter)) %>%
      kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
  )
}

# output_table_by_param(parameters[1])
# output_table_by_param(parameters[2])
# output_table_by_param(parameters[3])
# output_table_by_param(parameters[4])
# output_table_by_param(parameters[5])
# output_table_by_param(parameters[6])
output_table_by_param(parameters[7])
# output_table_by_param(parameters[8])
# output_table_by_param(parameters[9])
# output_table_by_param(parameters[10])
# output_table_by_param(parameters[11])
# output_table_by_param(parameters[12])
# output_table_by_param(parameters[13])

missing.two = (facet_data %>% group_by_at(parameters) %>% miss_var_summary %>% filter(n_miss != 0) %>% filter(variable == "total.RI"))[,c(1:6, 8:13, 15)]

descdist(missing.two$n_miss, discrete = T)
p1.two = glm.nb(n_miss ~ . , data = missing.two)
plot(p1.two, which = 2)
#summary(p1.two)
plot_summs(p1.two)
export_summs(p1.two, scale = T, error_format = "[{conf.low}, {conf.high}]")



```


