---
title: "Sensitivity Analysis - Assumptions and Interactions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(moments)
library(emmeans)
library(multcomp)
library(rcompanion)
library(forecast)
library(gamlss)
library(pscl)
library(MASS)
library(glmmTMB)
library(rstatix)
library(bbmle)
library(fitdistrplus)
library(lmtest)
library(betareg)
library(sandwich)
library(foreign)
library(car)
library(gplots)
library(rcompanion)

theme_set(theme_minimal())

# exp1 = read_csv("../output/exp1/run0_model-data.csv")
# exp2 = read_csv("../output/exp2/run0_model-data.csv")
# exp3 = read_csv("../output/exp3/run0_model-data.csv")
# 
# alldata = rbind(exp1, exp2, exp3)


#alldata = read_csv("../output/sub_sensitivity-data.csv")

alldata = alldata %>% filter(size != "size") %>%
  mutate(total.RI = as.numeric(total.RI), 
         total.CR = as.numeric(total.CR)) %>%
  group_by(max_use_intensity, max_artifact_carry, max_flake_size, max_nodules_size, blank_prob, scavenge_prob, overlap, mu, size_preference, flake_preference, min_suitable_flake_size, min_suitable_nodule_size, strict_selection) %>%
  mutate(exp = cur_group_id()) %>%
  filter(!is.na(total.RI))

parameters = c("max_use_intensity", "max_artifact_carry", "max_flake_size","max_nodules_size", "blank_prob", "scavenge_prob", "overlap","mu", "size_preference", "flake_preference","min_suitable_flake_size", "min_suitable_nodule_size", "strict_selection")

```

## Checking assumptions
- determining the distribution of recycling intensity values
- understanding the correlations between parameter values
```{r assumptions}
for(p in parameters) {
  print(c(unique(alldata[p])))
}

plotNormalHistogram(alldata$total.RI)
descdist(alldata$total.RI, discrete=F, boot=100)

var(alldata$total.RI)
mean(alldata$total.RI)

round(cor(alldata[,c(parameters, "total.RI")]), 2)

```



## Influence of parameters over time on recycling intensity at a landscape scale
```{r two-way interaction}

with(alldata, interaction.plot(model_year, max_use_intensity, total.RI))

with(alldata, interaction.plot(model_year, max_artifact_carry, total.RI, type="l"))

with(alldata, interaction.plot(model_year, max_flake_size, total.RI))

with(alldata, interaction.plot(model_year, max_nodules_size, total.RI))

with(alldata, interaction.plot(model_year, blank_prob, total.RI))

with(alldata, interaction.plot(model_year, scavenge_prob, total.RI))

with(alldata, interaction.plot(model_year, overlap, total.RI)) 

with(alldata, interaction.plot(model_year, mu, total.RI))

with(alldata, interaction.plot(model_year, size_preference, total.RI))

with(alldata, interaction.plot(model_year, flake_preference, total.RI))

with(alldata, interaction.plot(model_year, min_suitable_nodule_size, total.RI))

with(alldata, interaction.plot(model_year, min_suitable_flake_size, total.RI))

with(alldata, interaction.plot(model_year, strict_selection, total.RI))


```


## Influence of interaction between parameters over time on recycling intensity at the landscape scale
```{r three way interaction}
p1 = ggplot(alldata, aes(x = model_year, y = total.RI, color = as.factor(min_suitable_nodule_size))) + facet_grid(max_nodules_size~size_preference, labeller=label_both) + geom_smooth(se=F)
plot(p1)


p2 = ggplot(alldata, aes(x = model_year, y = total.RI, color = as.factor(min_suitable_flake_size))) + facet_grid(max_flake_size~size_preference, labeller=label_both) + geom_smooth(se=F)
plot(p2)


p4 = ggplot(alldata, aes(x = model_year, y = total.RI, color = as.factor(max_flake_size))) + facet_grid(min_suitable_flake_size~flake_preference, labeller=label_both) + geom_smooth(se=F)
plot(p4)


p5 = ggplot(alldata, aes(x = model_year, y = total.RI, color = as.factor(min_suitable_flake_size))) + facet_grid(size_preference~flake_preference, labeller=label_both) + geom_smooth(se=F)
plot(p5)


p6 = ggplot(alldata, aes(x = model_year, y = total.RI, color = as.factor(strict_selection))) + facet_grid(size_preference~flake_preference, labeller=label_both) + geom_smooth(se=F)
plot(p6)


```
