---
title: "parameter sensitivity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggpubr)
library(moments)
library(lsmeans)
library(multcomp)
library(rcompanion)
library(forecast)
theme_set(theme_minimal())

# exp1 = read_csv("../output/exp1/run0_model-data.csv")
# exp2 = read_csv("../output/exp2/run0_model-data.csv")
# exp3 = read_csv("../output/exp3/run0_model-data.csv")
# 
# alldata = rbind(exp1, exp2, exp3)
# 

alldata = alldata %>% mutate(
  total.RI = as.numeric(total.RI),
  total.CR = as.numeric(total.CR)
)

alldata = alldata %>% filter(!is.na(total.RI))

```

## Checking assumptions of recycling intensity output
```{r assumptions}

sample = dplyr::sample_n(alldata, 5000)
shapiro.test(sample$total.RI)

plotNormalHistogram(alldata$total.RI)
ggqqplot(sample$total.RI)

#transform data -- square root
alldata = alldata %>% mutate(trans.RI = sqrt(total.RI))

sample = dplyr::sample_n(alldata, 5000)
shapiro.test(sample$trans.RI)

plotNormalHistogram(alldata$trans.RI)
ggqqplot(sample$trans.RI)



```



## Influence of parameters over time on recycling intensity at a landscape scale

```{r interaction}

# with(tavg, interaction.plot(model_year, size, total.RI))
# summary(aov(total.RI ~ size*model_year, data=tavg))

with(alldata, interaction.plot(model_year, max_use_intensity, trans.RI))
summary(aov(trans.RI ~ max_use_intensity*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(max_use_intensity)*model_year, data=alldata), 
#         pairwise ~ as.factor(max_use_intensity), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, max_artifact_carry, trans.RI))
summary(aov(trans.RI ~ max_artifact_carry*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(max_artifact_carry)*model_year, data=alldata), 
#         pairwise ~ as.factor(max_artifact_carry), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, max_flake_size, trans.RI))
summary(aov(trans.RI ~ max_flake_size*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(max_flake_size)*model_year, data=alldata), 
#         pairwise ~ as.factor(max_flake_size), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, max_nodules_size, trans.RI))
summary(aov(trans.RI ~ max_nodules_size*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ max_nodules_size*model_year, data=alldata), 
#         pairwise ~ max_nodules_size, 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, blank_prob, trans.RI))
summary(aov(trans.RI ~ blank_prob*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(blank_prob)*model_year, data=alldata), 
#         pairwise ~ as.factor(blank_prob), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, scavenge_prob, trans.RI))
summary(aov(trans.RI ~ scavenge_prob*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(scavenge_prob)*model_year, data=alldata), 
#         pairwise ~ as.factor(scavenge_prob), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, overlap, trans.RI)) 
summary(aov(trans.RI ~ overlap*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(overlap)*model_year, data=alldata), 
#         pairwise ~ as.factor(overlap), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, mu, trans.RI))
summary(aov(trans.RI ~ mu*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(mu)*model_year, data=alldata), 
#         pairwise ~ as.factor(mu), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, size_preference, trans.RI))
summary(aov(trans.RI ~ size_preference*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ size_preference*model_year, data=alldata), 
#         pairwise ~ size_preference, 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, flake_preference, trans.RI))
summary(aov(trans.RI ~ flake_preference*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ flake_preference*model_year, data=alldata), 
#         pairwise ~ flake_preference, 
#         adjust = "tukey")


with(alldata, interaction.plot(model_year, min_suitable_nodule_size, trans.RI))
summary(aov(trans.RI ~ min_suitable_nodule_size*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(min_suitable_nodule_size)*model_year, data=alldata), 
#         pairwise ~ as.factor(min_suitable_nodule_size), 
#         adjust = "tukey")


with(alldata, interaction.plot(model_year, min_suitable_flake_size, trans.RI))
summary(aov(trans.RI ~ min_suitable_flake_size*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ as.factor(min_suitable_flake_size)*model_year, data=alldata), 
#         pairwise ~ as.factor(min_suitable_flake_size), 
#         adjust = "tukey")

with(alldata, interaction.plot(model_year, strict_selection, trans.RI))
summary(aov(trans.RI ~ strict_selection*model_year, data=alldata))
# lsmeans(lm(trans.RI ~ strict_selection*model_year, data=alldata), 
#         pairwise ~ strict_selection, 
#         adjust = "tukey")

```

## Influence of interaction between parameters over time on recycling intensity at the landscape scale
```{r three way interaction}


p1 = ggplot(alldata, aes(x = model_year, y = trans.RI, color = as.factor(min_suitable_nodule_size))) + facet_grid(~size_preference, labeller=label_both) + geom_smooth(se=F)
plot(p1)
summary(aov(trans.RI ~ size_preference*min_suitable_nodule_size*model_year, data=alldata))
tukey = lsmeans(lm(trans.RI ~ size_preference*as.factor(min_suitable_nodule_size)*model_year, data=alldata), 
                pairwise ~ size_preference:as.factor(min_suitable_nodule_size), 
                adjust = "tukey")
cld(tukey$lsmeans, 
    alpha = 0.05, 
    Letters=letters, 
    adjust="tukey")


p2 = ggplot(alldata, aes(x = model_year, y = trans.RI, color = as.factor(min_suitable_nodule_size))) + facet_grid(max_flake_size~size_preference, labeller=label_both) + geom_smooth(se=F)
plot(p2)
summary(aov(trans.RI ~ size_preference*min_suitable_nodule_size*max_flake_size*model_year, data=alldata))
tukey2 = lsmeans(lm(trans.RI ~ size_preference*as.factor(min_suitable_nodule_size)*as.factor(max_flake_size)*model_year, data=alldata), 
                pairwise ~ size_preference:as.factor(min_suitable_nodule_size):as.factor(max_flake_size), 
                adjust = "tukey")
cld(tukey2$lsmeans, 
    alpha = 0.05, 
    Letters=letters, 
    adjust="tukey")


p3 = ggplot(alldata, aes(x = model_year, y = trans.RI, color = as.factor(min_suitable_flake_size))) + facet_grid(~size_preference, labeller=label_both) + geom_smooth(se=F)
plot(p3)
summary(aov(trans.RI ~ size_preference*min_suitable_flake_size*model_year, data=alldata))
tukey3 = lsmeans(lm(trans.RI ~ size_preference*min_suitable_flake_size*model_year, data=alldata), 
                pairwise ~ size_preference:min_suitable_flake_size, 
                adjust = "tukey")
cld(tukey3$lsmeans, 
    alpha = 0.05, 
    Letters=letters, 
    adjust="tukey")


p4 = ggplot(alldata, aes(x = model_year, y = trans.RI, color = as.factor(max_flake_size))) + facet_grid(~flake_preference, labeller=label_both) + geom_smooth(se=F)
plot(p4)
summary(aov(trans.RI ~ flake_preference*max_flake_size*model_year, data=alldata))
tukey4 = lsmeans(lm(trans.RI ~ flake_preference*max_flake_size*model_year, data=alldata), 
                pairwise ~ flake_preference:max_flake_size, 
                adjust = "tukey")
cld(tukey4$lsmeans, 
    alpha = 0.05, 
    Letters=letters, 
    adjust="tukey")


p5 = ggplot(alldata, aes(x = model_year, y = trans.RI, color = as.factor(min_suitable_nodule_size))) + facet_grid(size_preference~flake_preference, labeller=label_both) + geom_smooth(se=F)
plot(p5)
summary(aov(trans.RI ~ size_preference*flake_preference*min_suitable_nodule_size*model_year, data=alldata))
tukey5 = lsmeans(lm(trans.RI ~ size_preference*flake_preference*min_suitable_nodule_size*model_year, data=alldata), 
                pairwise ~ size_preference:flake_preference:min_suitable_nodule_size, 
                adjust = "tukey")
cld(tukey5$lsmeans, 
    alpha = 0.05, 
    Letters=letters, 
    adjust="tukey")

p6 = ggplot(alldata, aes(x = model_year, y = trans.RI, color = as.factor(strict_selection))) + facet_grid(size_preference~flake_preference, labeller=label_both) + geom_smooth(se=F)
plot(p6)
summary(aov(trans.RI ~ size_preference*flake_preference*strict_selection*model_year, data=alldata))
tukey6 = lsmeans(lm(trans.RI ~ size_preference*flake_preference*strict_selection*model_year, data=alldata), 
                pairwise ~ size_preference:flake_preference:strict_selection, 
                adjust = "tukey")
cld(tukey6$lsmeans, 
    alpha = 0.05, 
    Letters=letters, 
    adjust="tukey")

```
